
version: 2

references:
  configure_npm: &configure_npm
    run: { name: 'Configure NPM', command: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'}

jobs:
  patternlab_build:
    working_directory: /var/www/code
    docker:
      - image: massgov/drupal-container:1.0.6-ci
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM Cache
          keys:
            - pl-npm-v1-{{ checksum "patternlab/styleguide/yarn.lock" }}
            - pl-npm-v1-
      - run: { name: 'NPM Install', command: 'cd patternlab/styleguide && yarn' }
      - save_cache:
          name: Save NPM cache
          key: pl-npm-v1-{{ checksum "patternlab/styleguide/yarn.lock" }}
          paths: [ styleguide/node_modules ]
      - run: { name: 'Generate style guide', command: 'php patternlab/styleguide/core/console --generate' }
      - run: { name: 'Build assets', command: 'cd patternlab/styleguide && node_modules/.bin/gulp prod' }
      - persist_to_workspace:
          root: /var/www/code
          paths: [patternlab]

  patternlab_test:
    working_directory: /home/circleci/patternlab
    docker:
      - image: circleci/python:2.7.14
    steps:
      - attach_workspace: {at: /home/circleci}
      - setup_remote_docker
      - run: docker-compose up --no-start web backstop
      - run: |
          docker cp ./ $(docker-compose ps -q backstop):/src/
          docker cp ./styleguide/public/. $(docker-compose ps -q web):/usr/share/nginx/html
      - run: docker-compose run backstop test
      - run:
          command: docker cp $(docker-compose ps -q backstop):/src/backstopjs/. ./backstopjs/
          when: always
      - store_artifacts:
          path: ./backstopjs
          destination: backstop
      - store_test_results:
          path: backstopjs/reports/ci

  patternlab_deploy:
    working_directory: /var/www/code
    docker:
      - image: massgov/drupal-container:1.0.6-ci
    steps:
      - add_ssh_keys
      - attach_workspace: {at: /var/www}
      - run:
        name: "Prepare Git"
        command: |
          git config --global user.email "ci.bot@mass.gov"
          git config --global user.name "MassGov Bot"
      - *configure_npm


workflows:
  version: 2
  build_branch:
    jobs:
      - patternlab_build
      - patternlab_deploy: {requires: [patternlab_build]}
      - patternlab_test: {requires: [patternlab_build]}

